import { FormEvent, useState } from 'react'
import { LoaderCircle, X } from 'lucide-react'
import { api } from '../lib/api'
import { messageOf } from '../lib/format'

export function AccountDialog({ onClose, onCreated }: { onClose: () => void; onCreated: () => void }) {
  const [provider, setProvider] = useState('qq'); const [email, setEmail] = useState(''); const [name, setName] = useState(''); const [password, setPassword] = useState(''); const [error, setError] = useState(''); const [busy, setBusy] = useState(false)
  async function submit(event: FormEvent) { event.preventDefault(); setBusy(true); setError(''); try { const result = await api.addAccount({ provider, email, display_name: name, username: email, auth: { type: ['gmail', 'outlook'].includes(provider) ? 'oauth2' : 'password', password } }); if ('authorization_url' in result) { location.href = result.authorization_url; return }; onCreated() } catch (err) { setError(messageOf(err)); setBusy(false) } }
  return <div className="modal-backdrop"><form onSubmit={submit} className="w-[min(92vw,460px)] rounded-panel bg-white p-7 shadow-glass-high"><div className="flex items-center justify-between"><div><p className="text-[10px] font-bold uppercase tracking-[.2em] text-pine/40">Connect</p><h2 className="font-serif text-3xl">连接邮箱</h2></div><button type="button" aria-label="关闭" onClick={onClose} className="icon-button"><X size={19} /></button></div><div className="mt-7 grid grid-cols-4 gap-2">{['qq', '163', 'gmail', 'outlook'].map(item => <button type="button" key={item} onClick={() => setProvider(item)} className={`rounded-2xl border px-2 py-3 text-xs font-bold uppercase transition ${provider === item ? 'border-pine bg-sage text-pine shadow-lift-2' : 'border-black/5 text-black/35 hover:border-black/10'}`}>{item}</button>)}</div><label htmlFor="account-name" className="field-label">显示名称</label><input id="account-name" className="input" value={name} onChange={e => setName(e.target.value)} placeholder="工作邮箱" />{!['gmail', 'outlook'].includes(provider) && <><label htmlFor="account-email" className="field-label">邮箱地址</label><input id="account-email" className="input" type="email" required value={email} onChange={e => setEmail(e.target.value)} /><label htmlFor="account-password" className="field-label">授权码</label><input id="account-password" className="input" type="password" required value={password} onChange={e => setPassword(e.target.value)} /><p className="mt-2 text-xs text-black/40">请使用邮箱服务商生成的客户端授权码，而非网页登录密码。</p></>}{['gmail', 'outlook'].includes(provider) && <div className="mt-6 rounded-card bg-sage/50 p-4 text-sm leading-6 text-pine">继续后将跳转到服务商授权页面。部署者必须已配置对应 OAuth Client ID 与 Secret。</div>}{error && <p className="mt-3 text-sm text-red-600">{error}</p>}<button disabled={busy} className="button-primary mt-7 w-full">{busy ? <LoaderCircle className="animate-spin" size={17} /> : '继续'}</button></form></div>
}
